// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiJ_E2nzv4quK0Sn---Li2N4Y4wkvJUrk',
    appId: '1:1006957514756:web:11c79c8d06ec99c5966551',
    messagingSenderId: '1006957514756',
    projectId: 'project-as-50cba',
    authDomain: 'project-as-50cba.firebaseapp.com',
    storageBucket: 'project-as-50cba.firebasestorage.app',
    measurementId: 'G-X5T4ERP0V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFcEL7R7N3O70ZT5cBPSXFykklpsqoRBs',
    appId: '1:1006957514756:android:c72cfff9df2e9f63966551',
    messagingSenderId: '1006957514756',
    projectId: 'project-as-50cba',
    storageBucket: 'project-as-50cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqHbRvasPu7QH6GyQkztdNbi9irh8KwA',
    appId: '1:1006957514756:ios:8183b0652151ede5966551',
    messagingSenderId: '1006957514756',
    projectId: 'project-as-50cba',
    storageBucket: 'project-as-50cba.firebasestorage.app',
    iosClientId: '1006957514756-qps3bgp0pna00mh6jnoove3rk8mntvlv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtqHbRvasPu7QH6GyQkztdNbi9irh8KwA',
    appId: '1:1006957514756:ios:8183b0652151ede5966551',
    messagingSenderId: '1006957514756',
    projectId: 'project-as-50cba',
    storageBucket: 'project-as-50cba.firebasestorage.app',
    iosBundleId: 'com.example.pas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiJ_E2nzv4quK0Sn---Li2N4Y4wkvJUrk',
    appId: '1:1006957514756:web:5c6f845934f7d6e6966551',
    messagingSenderId: '1006957514756',
    projectId: 'project-as-50cba',
    authDomain: 'project-as-50cba.firebaseapp.com',
    storageBucket: 'project-as-50cba.firebasestorage.app',
    measurementId: 'G-FLWQ3BEB1J',
  );
}